image: /home/fr909/Documents/ros_workspace/nice/robot_launch/world/map_level10_ros.pgm
resolution: 0.02
#resolution: 0.020000
size: [20 15 0.5]
origin: [ -0.062, -0.044, 0.000, 90.000 ]
occupied_thresh: 0.65
free_thresh: 0.196
negate: 0
